experiment_name: ""
note: ""
comment: ""

dataset: "../datasets/vimeo90k_compressai"

base_model: "bmshj2018-factorized"
model: "bmshj2018-factorized-batch-chan-decorr"

data:
  num_workers: 2
  batch_size: 8
  test_batch_size: 8
  patch_size: [ 256, 256,]

hparams:
  experiment:
    seed: 1234
    epochs: 200
  optimizer:
    learning_rate: 0.0001
    aux_learning_rate: 0.001
  criterion:
    lambda_: 0.001
  training:
    clip_max_norm: 1.0
  model:
    momentum_u: 0.0
    momentum_k: 0.0
    # Qualities 1-5
    N: 128
    M: 192
    # Qualities 6-8
    # N: 192
    # M: 320
